name: adhancron

services:
  adhan-manager:
    build: https://github.com/drhammadkhan/Adhancron.git#main
    image: adhancron:latest
    container_name: adhan-manager
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /DATA/AppData/adhan-manager:/data
    environment:
      HA_TOKEN: ""
      HA_URL: "http://homeassistant.local:8123"
      HA_ENTITY_ID: "media_player.bedroom_speaker"
      ADHAN_PLAYBACK_METHOD: "home_assistant"
      GOOGLE_CAST_HOST: ""
      GOOGLE_CAST_PORT: "8009"
      ADHAN_VOLUME: "0.8"
      ADHAN_LATITUDE: ""
      ADHAN_LONGITUDE: ""
      ADHAN_USE_ANNOUNCE: "true"
      ADHAN_PLAY_ATTEMPTS: "2"
      ADHAN_PLAYBACK_TIMEOUT: "15"
      ADHAN_PLAYBACK_POLL_INTERVAL: "1"
      ADHAN_MEDIA_CONTENT_TYPE: "audio/mpeg"
      TZ: "Europe/London"
    labels:
      icon: "https://raw.githubusercontent.com/drhammadkhan/Adhancron/main/casaos/adhan.jpg"

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Hammad Khan
  category: Utilities
  hostname: ""
  icon: "https://raw.githubusercontent.com/drhammadkhan/Adhancron/main/casaos/adhan.jpg"
  index: /
  is_uncontrolled: false
  port_map: "8090"
  scheme: http
  store_app_id: adhancron
  title:
    custom: Adhancron
    en_us: Adhancron
